name: imtihonoy
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.3
  expressions: ^0.2.5+2
  geolocator: ^13.0.2
  web: ^1.1.0
  math_expressions: ^2.6.0
  carousel_slider: ^5.0.0
  glass: ^2.0.0+2
  url_launcher: ^6.3.1
  lottie: ^3.1.3
  flutter_spinkit: ^5.2.1
  google_fonts: ^6.2.1
  flutter_staggered_grid_view: ^0.7.0
  hijri: ^3.0.0
  audioplayers: ^6.1.0
  cloud_firestore: ^5.5.0
  firebase_core: ^3.8.0
  provider: ^6.1.2
  flutter_sound: ^9.17.0
  intl: ^0.19.0
  flutter_launcher_icons: ^0.14.1
  video_player: ^2.9.2
  google_maps_flutter: ^2.10.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "images/erf.jpg"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "images/erf.jpg"
    background_color: "#FFFFFF"
    theme_color: "#000000"
  windows:
    generate: true
    image_path: "images/erf.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "images/erf.jpg"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - images/
    - assets/
    - videolar/
